### ISSUE TITLE
Metoda odigraj, razred Igra

### ISSUE THREAD

**Issue by KatarinaKoderman** [KatarinaKoderman/Dodgem#1]
Najprej: opravičujem se zaradi vnovične bolezni.
Nato: Metoda odigraj ni napisana in treba je še dobro razmisliti, kako jo bova implementirala. Najprej je treba pogledat x in y koordinate (kot je naredil profesor), nato pa je treba pogledat(/počakat?) na naslednji klik(?) igralca, da se ve, kam avtomobilček prestaviš. Svetujem posvetovanje s profesorjem, če prav razmišljam. Seveda dobrodošle tudi tvoje ideje.
Pri metodi poteze sta dva TODO-ja, ki sta analogna. Za zmago mora iti avtomobilček s plošče, torej je možna poteza tudi naprej, čeprav je avtomobilček že na robu plošče in na sami plošči ne more naprej.  Se doda še en pogoj ali morda še ena smer (ODSTRANI_S_PLOŠČE)? Vsekakor pa je kodo treba spremeniti (index out of range).

**Comment by andrejbauer** [comment]
Aha, ja, vajin GUI bo malo bolj zapleten, ker premikata figure. V ta namen smo vadili, kako se premika pikice po zaslonu. Vprašajta na vajah, lahko pa prideta tudi na govorilno uro, če se bo kompliciralo.
