### ISSUE TITLE
Kako uporabnik izvede potezo.

### ISSUE THREAD

**Issue by andrejbauer** [KatarinaKoderman/Dodgem#10]
V tem issue se dogovorita, kako uporabnik izvede potezo. Lahko gresta na kavo in se dogovorita v živo, ampak dogovor dokumentirajta v tem issue. Ko bo implementirano, zapreta issue s commitom, ki je implementiral dogovor.

**Comment by KatarinaKoderman** [comment]
Poteza uporabnika je sedaj sestavljena iz enega klika uporabnika. Figura igralca je sestavljena iz manjših likov, na katere uporabnik klikne in s tem izbere figuro in hkrati smer premika. 
Treba je še spremeniti območja, na katerih uporabnikov klik pomeni potezo. Trenutno se ne ujemajo povsem z izgledom figure igralca (klik na mejo).

**Comment by MatejJazbec** [comment]
Ko miška vstopi na območje zaznvanja klika miške, se rob trikotnika (ki predstavlja smer premika) obarva v zeleno: po kliku se poteza izvede, če je dovolje. Če poteza ni dovoljena, se ne izvede. ( #12 )

**Comment by KatarinaKoderman** [comment]
Poteza uporabnika je implementirana.
