### ISSUE TITLE
Označevanje dovoljenih potez.

### ISSUE THREAD

**Issue by KatarinaKoderman** [KatarinaKoderman/Dodgem#12]
Ko je na potezi HORIZONTAL, se ob premiku miške pobarvajo vsi manjši trikotniki (vse poteze), čeprav  niso vse dovoljene. Analogno za igralca VERTICAL. Pobarvati se morajo le dovoljene poteze.

**Comment by MatejJazbec** [comment]
Na govorilnih urah je bilo rečeno naj se vmesnik naprogramira brez upoštevanja dovoljenih potez. 
Zadevo se seveda lahko implementira: pred tem bi pa bilo smiselno popraviti/nadgraditi še nekaj manjših zadev, ki so od zgoraj omenjenega "issue" bolj moteče (drugače povedano: ki se ne tičejo le uporabnikove izkušnje).

**Comment by KatarinaKoderman** [comment]
Ko je na potezi igralec, se ob premiku miške obarva polje, ki označuje potezo. Ta ni nujno veljavna. Ob kliku na tako polje, ko poteza ni veljavna, se ne zgodi nič, na vrsti je še vedno isti igralec. Ko klikne veljavno potezo, se poteza izvrši.
Po dogovoru z asistentom je tako v redu.
