### ISSUE TITLE
Ocena pozicije

### ISSUE THREAD

**Issue by KatarinaKoderman** [KatarinaKoderman/Dodgem#14]
Računalnik ne izvaja optimalnih potez (sploh pri koncu). Domnevam, da je napaka v oceni pozicije, a je ne najdem. 
Pri ocenjevanju pozicije je število že izvedenih potez pravo (ne od kopije, čeprav bi moralo tudi to zadoščati). 
Ko se izračuna vrednost pozicije za igralca in nasprotnika, se vrednost nasprotnikove pozicije še razpolovi (da je manj vredna - tudi če ta del kode zakomentiramo, ne deluje, a morda je nepotreben).

**Comment by MatejJazbec** [comment]
Ocene še vedno niso optimalne: premike levo oz. desno upoštevamo kot enakovredne premikom naprej.

**Comment by KatarinaKoderman** [comment]
Ko računalnik vidi, da bo izgubil, se preneha truditi za zmago. To se zgodi proti koncu igre, ko je na plošči le nekaj figur. Ocena je sicer dobra, računalnik dobro igra.
