### ISSUE TITLE
Narobe se sklicujeta na ime datoteke z zvočnim zapisom

### ISSUE THREAD

**Issue by andrejbauer** [KatarinaKoderman/Dodgem#15]
V `GlavnoOkno.java` imata okoli 60. vrstice napisano:

	static File soundFile = new File("Dodgem\\resources\\Insert-Coins-Jake-Wright.wav");

Na Macu se uporablja `/` namesto `\\` in mi zaradi tega program ne dela. Uporabiti je treba nekaj takega kot 4. rešitev v [tem odgovoru](https://stackoverflow.com/a/15749281/394327).

**Comment by KatarinaKoderman** [comment]
Traja kar nekaj časa, da se začne zvok predvajati.

**Comment by KatarinaKoderman** [comment]
@andrejbauer Bi lahko prosim preverili, če tole sedaj dela na vašem operacijskem sistemu?

**Comment by MatejJazbec** [comment]
@KatarinaKoderman , prosim preverite če vam po spremembi še vedno deluje.

**Comment by KatarinaKoderman** [comment]
Preizkušeno na macu - deluje.

**Comment by MatejJazbec** [comment]
super!
________________________________
